version: "3"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
